### ISSUE TITLE
nice sort of a chad plugin, command to initiate screensaver?

### ISSUE THREAD

**Issue by daUnknownCoder** [tamton-aquib/zone.nvim#12]
like `:lua require("zone").treadmill(<opts>)` that would b gr8 after solving the unending uneditable animation bug #3

**Comment by tamton-aquib** [comment]
Heyyo @daUnknownCoder,

That should be possible with something like:
```lua
require("zone.styles.treadmill").start()
```

But there are already commands that comes with zone.nvim, so you could easily start the styles:

![image](https://github.com/tamton-aquib/zone.nvim/assets/77913442/b1574ee2-f750-4c15-805f-5f7f2a98bf84)

**Comment by daUnknownCoder** [comment]
Hey @tamton-aquib, I am having a few problems with ending the animation, `q`, `:w`, `:`, doesn't help in shutting it down

**Comment by tamton-aquib** [comment]
Sure, lets track it in #3.

If the current issue is resolved, feel free to close it 👍🏻
