### ISSUE TITLE
Could you provide a command to manually trigger the animation?

### ISSUE THREAD

**Issue by nyngwang** [tamton-aquib/zone.nvim#2]
As title. Since more animation will be added, it would be good to accept an argument for that command to specify which animation to trigger. This would be really cool when done, thank you!

**Comment by loicreynier** [comment]
The command is already [here](https://github.com/tamton-aquib/zone.nvim/blob/c0f0cfe5b2415c1f0322487e753aa60f0b657256/plugin/zone.lua#L2-L10), try `:Zone dvd`.

**Comment by nyngwang** [comment]
@loicreynier Great! Then let me close this ;)
