### ISSUE TITLE
The first line doesn't get animated.

### ISSUE THREAD

**Issue by nyngwang** [tamton-aquib/zone.nvim#4]
It seems that you're assuming people all use a plugin to show the buffer name. I don't use that so I got the first line intact (as shown by the img below). It would be better to add detection of any bufferline plugin when adding the offset.

<img src="https://user-images.githubusercontent.com/24765272/204531387-90949b9c-633e-4402-8545-b9f43c04456c.png" width="500">

**Comment by tamton-aquib** [comment]
Heyyo @nyngwang,

> It seems that you're assuming people all use a plugin to show the buffer name

Ah thats true, Ive been thinking about keeping some checks for laststatus, showtabline, signcolumn, etc.
Will add it to the todo list 😅

**Comment by nyngwang** [comment]
Great to know. Thanks for your explanation!

**Comment by tamton-aquib** [comment]
Hey @nyngwang , I have pushed a small change, let me know if it works 😅

**Comment by nyngwang** [comment]
@tamton-aquib Yes, it works. Let me close this issue.
