### ISSUE TITLE
Error on executing ":Zone dvd"

### ISSUE THREAD

**Issue by Geostartico** [tamton-aquib/zone.nvim#6]
All the other options seem to work as expected , however the dvd throws this error:
Error executing Lua callback: <user>/.vim/plugged/zone.nvim/lua/zone/styles/dvd.lua:33: attempt to index upvalue 'local_opts' (a nil value)                                                            
stack traceback:
        <user>/.vim/plugged/zone.nvim/lua/zone/styles/dvd.lua:33: in function 'start'
        /home/<user>/.vim/plugged/zone.nvim/plugin/zone.lua:3: in function </home/<user>/.vim/plugged/zone.nvim/plugin/zone.lua:2>

**Comment by tamton-aquib** [comment]
Heyyo @Geostartico ,
Can u update the plugin and check again? 😅

**Comment by Geostartico** [comment]
Now it works with no issue :)
